### ISSUE TITLE
Images aren't loaded due to 404s

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/spring-asciidoctor-backends#11]
I think the images are being looked for in the wrong place. For example, on https://docs.spring.io/spring-boot/docs/2.5.0-SNAPSHOT/reference/htmlsingle/ there are 404s for a couple of SVGs:

- https://docs.spring.io/spring-boot/docs/2.5.0-SNAPSHOT/reference/img/banner-logo.svg
- https://docs.spring.io/spring-boot/docs/2.5.0-SNAPSHOT/reference/img/doc-background.svg

I think the correct URLs are the following:

- https://docs.spring.io/spring-boot/docs/2.5.0-SNAPSHOT/reference/htmlsingle/img/banner-logo.svg
- https://docs.spring.io/spring-boot/docs/2.5.0-SNAPSHOT/reference/htmlsingle/img/doc-background.svg

**Comment by philwebb** [comment]
This seems to be unique to Safari. The images all load fine in Chrome and Firefox

**Comment by wilkinsona** [comment]
I'm still getting 404s for the following in Boot's docs:

- `"../img/doc-background.svg"`
- `"../img/doc-background-dark.svg"`
- `"../img/banner-logo.svg"`

These are fine, though:

- `"../img/octicons-16.svg#view-sun"`
- `../img/octicons-16.svg#view-info`

The octicons links suggest that the quoting doesn't matter.

**Comment by wilkinsona** [comment]
I think the problem may be the use of custom properties. The svgs where the links break are all using custom properties, whereas the URL of the octicons SVG is always defined directly. When custom properties are used, Safari seems to use links that are relative to the HTML: https://stackoverflow.com/questions/65199329/css-variable-url-fallback-relative-path-different-in-safari-to-other-browsers.
