### ISSUE TITLE
Improve HighlightJS CSS for JSON

### ISSUE THREAD

**Issue by toedter** [spring-io/spring-asciidoctor-backends#31]
In dark mode, only white for keys and blue for values,
in light mode everything is black.

It would be great if JSON would be a bit more "colorful", e.g. also render numbers in another color than strings.

**Comment by philwebb** [comment]
Thanks for the suggestion, I've tweaked the CSS a little. It now looks like this:

<img width="732" alt="Screen Shot 2021-04-24 at 12 16 25 PM" src="https://user-images.githubusercontent.com/519772/115970443-45365c80-a4f7-11eb-93dd-8e6a849a78a4.png">

It's still not that colorful, but it's closer to the GitHub look:

<img width="853" alt="Screen Shot 2021-04-24 at 12 20 10 PM" src="https://user-images.githubusercontent.com/519772/115970481-7151dd80-a4f7-11eb-81ff-edeb878c3b45.png">

**Comment by toedter** [comment]
Thx @philwebb
