### ISSUE TITLE
Horizontal Scroolbar at the Bottom of the Navigation Pane

### ISSUE THREAD

**Issue by toedter** [spring-io/spring-asciidoctor-backends#48]
When you scroll down the document, a horizontal scrollbar appears at the bottom of the navigation pane.
An example: https://toedter.github.io/spring-hateoas-jsonapi/snapshot/reference/

**Comment by philwebb** [comment]
Can you provide details of your web browser and also provide a screenshot. I'm not seeing a scrollbar locally.

**Comment by toedter** [comment]
Sure:
OS: Windows 10
Browser: (Up to date) Google Chrome, Version 90.0.4430.212 (Official Build) (64-bit)

I checked with Firefox: Looks ok, no horizontal scroll bars, but with Chrome:

**Comment by philwebb** [comment]
Thanks. It also happens on MacOS with Chrome
