### ISSUE TITLE
How to configure in Kotlin Gradle script? 

### ISSUE THREAD

**Issue by auto-generated** [spring-io/spring-asciidoctor-backends#53]
I don’t know how to configure and use it in `build.gradle.kts`, can you give me an example

**Comment by wilkinsona** [comment]
That's really a Gradle Kotlin DSL question. There are lots of excellent examples in Gradle's documentation of [creating a new configuration and adding a dependency to it](https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:resolvable-consumable-configs), [customizing a task](https://docs.gradle.org/current/samples/sample_building_java_libraries.html#customize_the_library_jar), etc. What in particular are you struggling with and what have you tried already?

**Comment by auto-generated** [comment]
@wilkinsona Thank you, according to the document you sent, I have successfully configured and run
