### ISSUE TITLE
Level 3 Section Title not show in left menu

### ISSUE THREAD

**Issue by apoollo** [spring-io/spring-asciidoctor-backends#58]
![asciidoctor](https://user-images.githubusercontent.com/49150327/155504758-9dbbefad-c0fd-4578-a0ad-6ac3e0076c58.png)
3级章节没有显示在左侧菜单里，没有找到相关配置； 请赐教

**Comment by wilkinsona** [comment]
I suspect you haven't configured your document's `toclevels`. For example, Spring Boot's documentation uses `:toclevels: 4` with this backend [and shows four levels in the table of contents](https://docs.spring.io/spring-boot/docs/2.5.9/reference/htmlsingle/#getting-started.installing.java.maven).

**Comment by apoollo** [comment]
thank you  very much ; up ssue has been resolved ;  another question , how to set up html  "shortcut icon" and change spring icon ; 
非常感谢您如此快速的回复，上面的问题已经解决。另外的问题： 如何设置html tab 图标，以及更改spring 图标；
![icon](https://user-images.githubusercontent.com/49150327/155512253-366ce7b7-3536-412a-a52d-36bba0bf6406.png)

**Comment by wilkinsona** [comment]
The purpose of this problem is to produce Spring-branded documentation. If you want to use it for another purpose then you are, of course, free to modify it to meet your needs but such usage isn't something that we intend to support or that we can afford spend time on.

**Comment by apoollo** [comment]
thank you
