### ISSUE TITLE
FontAwesome icons not rendered correctly

### ISSUE THREAD

**Issue by odrotbohm** [spring-io/spring-asciidoctor-backends#65]
In contrast to the standard HTML backend, our generated documents are missing the directive to include the FontAwesome icon CSS file

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
```

There's [code](https://github.com/spring-io/spring-asciidoctor-backends/blob/main/src/main/ruby/lib/spring-asciidoctor-backends/spring-html5-converter.rb) that sets the icons to be font-based by default, but also deactivates remote fonts (a line below). If we really want the latter, we'd have to ship FontAwesome CSS and fonts [ourselves](https://docs.asciidoctor.org/asciidoctor/latest/html-backend/local-font-awesome/).

**Comment by philwebb** [comment]
Setting `icons` to `font` might be an oversight in our CSS. I can't remember why we did it, it might have been to get HTML markup that was easier to style even though we don't directly use font-awsome. For the limited "icons" that we do use, we have a single `octicons-16.svg` file.

Are you wanting to use font-awesome directly in markup? Or are you finding one of the existing admon icons isn't correct?

**Comment by odrotbohm** [comment]
Yes, the [sources I deal with](https://raw.githubusercontent.com/spring-projects-experimental/spring-modulith/main/src/docs/asciidoc/10-fundamentals.adoc) contain `icon:folder[]` expressions that render fine when using the standard HTML backend.

**Comment by philwebb** [comment]
I remember a bit more about why the font support is so odd. The CSS for this backend is based on Antora and they [don't currently have support for font-awesome](https://gitlab.com/antora/antora-ui-default/-/issues/58). We use the `:icons: font` attribute to generate CSS we can use but actually implement `fa` CSS class by loading images from an SVG file.

I've got something hacked locally that reinstates font-awsome 4 support but I need to do some more testing before it can be merged.

**Comment by philwebb** [comment]
@odrotbohm I've pushed something, but you'll need to set a `:iconfont-fontawesome:` attribute to enable the feature. Let me know if it doesn't work.

**Comment by odrotbohm** [comment]
I can confirm this works as described! Thanks, Phil! 🙇
