### ISSUE TITLE
Supporting more languages from highlight.js

### ISSUE THREAD

**Issue by eallais** [spring-io/spring-asciidoctor-backends#78]
I am wondering how to add more languages that the one currently supported by this project.
I did not mange to include new highlight.js languages, do we need an enhancement to register them ?
Thanks

**Comment by philwebb** [comment]
The supported languages are [here](https://github.com/spring-io/spring-asciidoctor-backends/blob/44f1c61a238125ea3c176925408f38d345508865/src/main/js/site/highlight.js#L22-L43), however, I've not been able to upgrade to a recent highlight.js (see https://github.com/spring-io/spring-asciidoctor-backends/commit/d2d09faf673424e0cf10d869767e48681ff8d595)

**Comment by eallais** [comment]
Do you have a simple procedure to add new highlight.js languages such as PowerShell or Properties or I need to fork the project and add them myself ?

Thanks

**Comment by philwebb** [comment]
You should find `properties` are already there. I'm happy to add `powershell`.

**Comment by eallais** [comment]
Great in that case it would be great to also have Windows Batch language support (called **dos** in highlight.js)

Thank you

**Comment by eallais** [comment]
BTW, do we have a particular reason to declare twice **bash** with another highlight.je language ?

https://github.com/spring-io/spring-asciidoctor-backends/blob/44f1c61a238125ea3c176925408f38d345508865/src/main/js/site/highlight.js#L40

**Comment by philwebb** [comment]
That looks like an error
